name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make debug
    - name: run
      run: ./thoth-debug.exe debug
    - name: test
      run: ./thoth-debug.exe test
    - name: clean
      run: make clean
